{% set name = "awssert" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/awssert-{{ version }}.tar.gz
  sha256: 261bab609a36bef04096c8ca777159e5b28e53c2473f215b406dc2444e0c9102

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - boto3 <=1.17.49
    - docker-py <=4.4.2
    - ecdsa <0.15
    - mock <=4.0.3
    - moto
    - pyasn1
    - pytest <=6.2.3
    - python >={{ python_min }}
    - python-dateutil <=2.8.1
    - rsa
    - werkzeug <2.0.0

test:
  imports:
    - awssert
    - test
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/TSNoble/awssert
  summary: Declarative assertions for AWS
  dev_url: https://github.com/TSNobleSoftware/awssert
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
